# -*- coding: utf-8 -*-
"""House Price Model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OKIPAXvd6TLQDFIDu0R7BTzsku9k0mv1
"""

pip install flask pandas scikit-learn numpy

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
import pickle

df = pd.read_csv('prices.csv')

print("Dataset shape:", df.shape)
print("\nFirst 5 rows:")
print(df.head())
print("\nDataset info:")
print(df.info())
print("\nStatistical summary:")
print(df.describe())

X = df[['Rooms', 'Distance']]  # Features
y = df['Value'] # Target

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = LinearRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("\nModel Evaluation:")
print("Coefficients:", model.coef_)
print("Intercept:", model.intercept_)
print("Mean Squared Error:", mean_squared_error(y_test, y_pred))
print("R-squared Score:", r2_score(y_test, y_pred))

with open('house_price_model.pkl', 'wb') as file:
    pickle.dump(model, file)
print("\nModel saved as 'house_price_model.pkl'")

sample_data = pd.DataFrame([[7.5, 2.0]], columns=['Rooms', 'Distance'])

prediction = model.predict(sample_data)
print(f"\nSample Prediction - Rooms: 7.5, Distance: 2.0")
print(f"Predicted Value: ${prediction[0]:.2f} thousand")

# HOUSE PRICE PREDICTION MODEL TRAINING
# Data Preprocessing and Model Training

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error
import pickle
import warnings
warnings.filterwarnings('ignore')

plt.figure(figsize=(15, 4))

plt.subplot(1, 3, 1)
plt.hist(df['Rooms'], bins=20, edgecolor='black', alpha=0.7)
plt.title('Distribution of Rooms')
plt.xlabel('Number of Rooms')
plt.ylabel('Frequency')

plt.subplot(1, 3, 2)
plt.hist(df['Distance'], bins=20, edgecolor='black', alpha=0.7)
plt.title('Distribution of Distance')
plt.xlabel('Distance from City Center (km)')
plt.ylabel('Frequency')

plt.subplot(1, 3, 3)
plt.hist(df['Value'], bins=20, edgecolor='black', alpha=0.7)
plt.title('Distribution of House Values')
plt.xlabel('House Value ($1000)')
plt.ylabel('Frequency')

plt.tight_layout()
plt.savefig('data_distributions.png')
plt.show()

# Correlation analysis
print("\n3. CORRELATION ANALYSIS...")
correlation_matrix = df.corr()
print("Correlation Matrix:")
print(correlation_matrix)

plt.figure(figsize=(8, 6))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', center=0)
plt.title('Feature Correlation Heatmap')
plt.savefig('correlation_heatmap.png')
plt.show()

# Model Training
print("\n4. TRAINING MACHINE LEARNING MODEL...")

# Prepare features and target
X = df[['Rooms', 'Distance']]  # Features
y = df['Value']                # Target variable

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)
print(f"Training set size: {X_train.shape[0]} samples")
print(f"Testing set size: {X_test.shape[0]} samples")

# Choose Linear Regression algorithm
print("\nChosen Algorithm: Linear Regression")
print("Reason: Linear Regression is suitable because:")
print("1. House price prediction typically has linear relationships")
print("2. It's interpretable - we can see how each feature affects price")
print("3. Works well with continuous numerical data")
print("4. Simple yet effective for this problem")

# Create and train the model
model = LinearRegression()
model.fit(X_train, y_train)

# Make predictions
y_pred = model.predict(X_test)

# Model Evaluation
print("\n5. MODEL EVALUATION...")

# Performance metrics
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"Mean Squared Error (MSE): {mse:.2f}")
print(f"Root Mean Squared Error (RMSE): {rmse:.2f}")
print(f"Mean Absolute Error (MAE): {mae:.2f}")
print(f"R-squared Score: {r2:.4f}")

print("\nInterpretation:")
print(f"• R-squared of {r2:.4f} means {r2*100:.1f}% of variance is explained")
print(f"• Average prediction error: ${rmse:.2f} thousand")
print(f"• Typical error range: ±${mae:.2f} thousand")

# Model coefficients
print("\n6. MODEL COEFFICIENTS (Feature Importance):")
print(f"Intercept: {model.intercept_:.2f}")
print(f"Coefficient for Rooms: {model.coef_[0]:.2f}")
print(f"Coefficient for Distance: {model.coef_[1]:.2f}")

print("\nInterpretation:")
print(f"• Each additional room adds ${model.coef_[0]:.2f} thousand to price")
print(f"• Each km farther from city reduces price by ${abs(model.coef_[1]):.2f} thousand")

# Saving Model
print("\n7. SAVING MODEL...")

with open('house_price_model.pkl', 'wb') as file:
    pickle.dump(model, file)

print("Model saved as 'house_price_model.pkl'")

# Testing the Model
print("\n8. TESTING MODEL WITH SAMPLE DATA...")

# Test cases
test_cases = [
    [4.0, 1.5],   # Small house, close to city
    [7.5, 2.0],   # Medium house, moderate distance
    [8.0, 10.0],  # Large house, far from city
]

for i, (rooms, distance) in enumerate(test_cases, 1):
    test_data = pd.DataFrame([[rooms, distance]], columns=['Rooms', 'Distance'])
    prediction = model.predict(test_data)[0]
    print(f"\nTest Case {i}:")
    print(f"  Rooms: {rooms}, Distance: {distance} km")
    print(f"  Predicted Price: ${prediction:.2f} thousand")

print("\n" + "="*50)
print("MODEL TRAINING COMPLETE!")
print("="*50)

HOUSE PRICE PREDICTION FLASK APPLICATION
# Web App Implementation

from flask import Flask, render_template, request, jsonify
import pickle
import pandas as pd
import numpy as np
import os
pip install flask pandas scikit-learn numpy

app = Flask(__name__)

# Load the trained model
try:
    with open('house_price_model.pkl', 'rb') as file:
        model = pickle.load(file)
    print("✓ Model loaded successfully!")
    print(f"Model coefficients: {model.coef_}")
    print(f"Model intercept: {model.intercept_}")
except Exception as e:
    print(f"✗ Error loading model: {e}")
    model = None

# Routes
@app.route('/')
def home():
    """Home page with prediction form"""
    return render_template('index.html',
                         title="House Price Predictor",
                         model_loaded=model is not None)

@app.route('/predict', methods=['POST'])
def predict():
    """Handle prediction requests"""
    if model is None:
        return jsonify({'error': 'Model not loaded'}), 500

    try:
        # Get form data
        rooms = float(request.form.get('rooms', 0))
        distance = float(request.form.get('distance', 0))

        # Validate input ranges (Question 3.i)
        if rooms < 1 or rooms > 15:
            return render_template('index.html',
                                error=f"Number of rooms ({rooms}) is outside typical range (1-15)")

        if distance < 0.1 or distance > 20:
            return render_template('index.html',
                                error=f"Distance ({distance} km) is outside typical range (0.1-20 km)")

        # Prepare data for prediction
        features = pd.DataFrame([[rooms, distance]],
                              columns=['Rooms', 'Distance'])

        # Make prediction
        prediction = model.predict(features)[0]

        # Round to 2 decimal places
        prediction = round(prediction, 2)

        # Calculate feature contributions
        room_contribution = rooms * model.coef_[0]
        distance_contribution = distance * model.coef_[1]
        base_price = model.intercept_

        return render_template('index.html',
                             prediction=f"${prediction} thousand",
                             rooms=rooms,
                             distance=distance,
                             room_contribution=f"${room_contribution:.2f}",
                             distance_contribution=f"${distance_contribution:.2f}",
                             base_price=f"${base_price:.2f}",
                             show_details=True)

    except ValueError:
        return render_template('index.html',
                             error="Please enter valid numbers for rooms and distance")
    except Exception as e:
        return render_template('index.html',
                             error=f"Prediction error: {str(e)}")

@app.route('/api/predict', methods=['POST'])
def api_predict():
    """API endpoint for predictions (bonus feature)"""
    if model is None:
        return jsonify({'error': 'Model not loaded'}), 500

    try:
        data = request.get_json()
        rooms = float(data.get('rooms', 0))
        distance = float(data.get('distance', 0))

        features = pd.DataFrame([[rooms, distance]],
                              columns=['Rooms', 'Distance'])
        prediction = model.predict(features)[0]

        return jsonify({
            'prediction': round(prediction, 2),
            'units': 'thousands of dollars',
            'features': {
                'rooms': rooms,
                'distance': distance
            }
        })

    except Exception as e:
        return jsonify({'error': str(e)}), 400

@app.route('/about')
def about():
    """About page explaining the model"""
    if model is None:
        coeff = [0, 0]
        intercept = 0
    else:
        coeff = model.coef_.tolist()
        intercept = model.intercept_

    return render_template('about.html',
                         coefficients=coeff,
                         intercept=intercept,
                         r_squared=0.85)  # Replace with actual value

@app.route('/model_info')
def model_info():
    """API endpoint to get model information"""
    if model is None:
        return jsonify({'error': 'Model not loaded'}), 500

    return jsonify({
        'algorithm': 'Linear Regression',
        'features': ['Rooms', 'Distance'],
        'coefficients': model.coef_.tolist(),
        'intercept': model.intercept_,
        'equation': f"Price = {model.intercept_:.2f} + {model.coef_[0]:.2f}*Rooms + {model.coef_[1]:.2f}*Distance"
    })

# Run Application
from flask import Flask, render_template, request
import pickle
import pandas as pd
import os

app = Flask(__name__)

# Try to load model
try:
    with open('house_price_model.pkl', 'rb') as f:
        model = pickle.load(f)
    print("Model loaded successfully!")
except:
    print("Model not found, running in demo mode")
    model = None

@app.route('/')
def home():
    return "Flask is working! Add your HTML template here."

@app.route('/test')
def test():
    return "Test page working!"

if __name__ == '__main__':
    app.run(debug=True, port=5000, use_reloader=False)

import os
from flask import Flask

# Create Flask application
app = Flask(__name__)

# Define your routes here
@app.route('/')
def home():
    return "House Price Prediction Web App"

# Run Application
if __name__ == '__main__':
    port = int(os.environ.get('PORT', 5000))
    print(f"\n{'='*50}")
    print("HOUSE PRICE PREDICTION WEB APP")
    print("="*50)
    print(f"Starting server on port {port}...")
    print(f"Visit: http://localhost:{port}")
    print("="*50)
    app.run(debug=True, host='0.0.0.0', port=port)

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
</head>
<body>
    <div class="container">
        <header>
            <h1><i class="fas fa-home"></i> House Price Predictor</h1>
            <p class="subtitle">Predict house prices based on rooms and distance from city center</p>
        </header>

        <div class="main-content">
            <div class="prediction-form">
                <h2><i class="fas fa-calculator"></i> Price Prediction</h2>

                {% if not model_loaded %}
                <div class="error-message">
                    <i class="fas fa-exclamation-triangle"></i>
                    Model not loaded. Please check if house_price_model.pkl exists.
                </div>
                {% endif %}

                {% if error %}
                <div class="error-message">
                    <i class="fas fa-exclamation-circle"></i> {{ error }}
                </div>
                {% endif %}

                <form action="/predict" method="POST">
                    <div class="form-group">
                        <label for="rooms">
                            <i class="fas fa-door-open"></i> Number of Rooms:
                        </label>
                        <input type="number"
                               id="rooms"
                               name="rooms"
                               step="0.1"
                               min="1"
                               max="15"
                               placeholder="e.g., 7.5"
                               value="{{ rooms if rooms else '' }}"
                               required>
                        <small class="hint">Typical range: 1-15 rooms</small>
                    </div>

                    <div class="form-group">
                        <label for="distance">
                            <i class="fas fa-road"></i> Distance from City Center (km):
                        </label>
                        <input type="number"
                               id="distance"
                               name="distance"
                               step="0.1"
                               min="0.1"
                               max="20"
                               placeholder="e.g., 2.0"
                               value="{{ distance if distance else '' }}"
                               required>
                        <small class="hint">Typical range: 0.1-20 km</small>
                    </div>

                    <button type="submit" class="predict-btn">
                        <i class="fas fa-chart-line"></i> Predict Price
                    </button>
                </form>

                {% if prediction %}
                <div class="result-box">
                    <h3><i class="fas fa-dollar-sign"></i> Prediction Result</h3>
                    <div class="prediction-value">{{ prediction }}</div>

                    {% if show_details %}
                    <div class="details">
                        <p><strong>Input Details:</strong></p>
                        <ul>
                            <li>Rooms: {{ rooms }}</li>
                            <li>Distance: {{ distance }} km</li>
                        </ul>

                        <p><strong>How it's calculated:</strong></p>
                        <div class="calculation">
                            <p>Base Price: {{ base_price }}</p>
                            <p>Rooms Contribution: {{ room_contribution }} ({{ rooms }} × coefficient)</p>
                            <p>Distance Contribution: {{ distance_contribution }} ({{ distance }} × coefficient)</p>
                        </div>
                    </div>
                    {% endif %}
                </div>
                {% endif %}
            </div>

            <div class="info-section">
                <h2><i class="fas fa-info-circle"></i> How It Works</h2>

                <div class="info-card">
                    <h3><i class="fas fa-database"></i> About the Model</h3>
                    <p>This model uses Linear Regression trained on historical house price data.</p>
                    <ul>
                        <li><strong>Algorithm:</strong> Linear Regression</li>
                        <li><strong>Features:</strong> Rooms & Distance</li>
                        <li><strong>Training Data:</strong> {{ '{:,}'.format(250) }} houses</li>
                        <li><strong>Accuracy:</strong> ~85% R-squared</li>
                    </ul>
                </div>

                <div class="info-card">
                    <h3><i class="fas fa-lightbulb"></i> Tips for Best Results</h3>
                    <ul>
                        <li>Enter values within typical ranges</li>
                        <li>More rooms generally increase price</li>
                        <li>Greater distance generally decreases price</li>
                        <li>Results are estimates based on historical patterns</li>
                    </ul>
                </div>

                <div class="navigation">
                    <a href="/about" class="nav-btn">
                        <i class="fas fa-chart-bar"></i> View Model Details
                    </a>
                    <a href="/model_info" class="nav-btn" target="_blank">
                        <i class="fas fa-code"></i> API Endpoint
                    </a>
                </div>
            </div>
        </div>

        <footer>
            <p>Machine Learning Model Deployment | Lab 8 Part 2</p>
            <p class="model-status">
                Model Status:
                <span class="status-indicator {{ 'active' if model_loaded else 'inactive' }}">
                    {{ 'Active' if model_loaded else 'Inactive' }}
                </span>
            </p>
        </footer>
    </div>
</body>
</html>

# Website style
* {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
}

body {
    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
    background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
    min-height: 100vh;
    display: flex;
    justify-content: center;
    align-items: center;
    padding: 20px;
    color: #333;
}

.container {
    background: white;
    border-radius: 20px;
    box-shadow: 0 20px 60px rgba(0, 0, 0, 0.15);
    width: 100%;
    max-width: 1200px;
    overflow: hidden;
    animation: fadeIn 0.5s ease-out;
}

@keyframes fadeIn {
    from { opacity: 0; transform: translateY(-20px); }
    to { opacity: 1; transform: translateY(0); }
}

/* Header */
header {
    background: linear-gradient(to right, #667eea, #764ba2);
    color: white;
    padding: 30px;
    text-align: center;
}

header h1 {
    font-size: 2.5em;
    margin-bottom: 10px;
    display: flex;
    align-items: center;
    justify-content: center;
    gap: 15px;
}

.subtitle {
    font-size: 1.1em;
    opacity: 0.9;
    max-width: 600px;
    margin: 0 auto;
}

/* Main Content */
.main-content {
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 30px;
    padding: 30px;
}

@media (max-width: 900px) {
    .main-content {
        grid-template-columns: 1fr;
    }
}

/* Form Styles */
.prediction-form {
    background: #f8f9fa;
    padding: 25px;
    border-radius: 15px;
    box-shadow: 0 5px 15px rgba(0,0,0,0.05);
}

.prediction-form h2 {
    color: #667eea;
    margin-bottom: 25px;
    display: flex;
    align-items: center;
    gap: 10px;
}

.form-group {
    margin-bottom: 25px;
}

label {
    display: block;
    margin-bottom: 8px;
    font-weight: 600;
    color: #555;
    display: flex;
    align-items: center;
    gap: 10px;
}

input[type="number"] {
    width: 100%;
    padding: 15px;
    border: 2px solid #e0e0e0;
    border-radius: 10px;
    font-size: 16px;
    transition: all 0.3s;
    background: white;
}

input[type="number"]:focus {
    outline: none;
    border-color: #667eea;
    box-shadow: 0 0 0 3px rgba(102, 126, 234, 0.2);
}

.hint {
    display: block;
    margin-top: 5px;
    color: #888;
    font-size: 0.9em;
}

/* Buttons */
.predict-btn {
    background: linear-gradient(to right, #667eea, #764ba2);
    color: white;
    border: none;
    padding: 18px 30px;
    border-radius: 10px;
    font-size: 18px;
    font-weight: 600;
    cursor: pointer;
    width: 100%;
    display: flex;
    align-items: center;
    justify-content: center;
    gap: 10px;
    transition: all 0.3s;
    margin-top: 10px;
}

.predict-btn:hover {
    transform: translateY(-3px);
    box-shadow: 0 10px 25px rgba(102, 126, 234, 0.3);
}

.predict-btn:active {
    transform: translateY(-1px);
}

/* Result Box */
.result-box {
    margin-top: 30px;
    padding: 25px;
    background: white;
    border-radius: 15px;
    border-left: 5px solid #4CAF50;
    box-shadow: 0 5px 15px rgba(0,0,0,0.05);
    animation: slideIn 0.5s ease-out;
}

@keyframes slideIn {
    from { opacity: 0; transform: translateY(20px); }
    to { opacity: 1; transform: translateY(0); }
}

.prediction-value {
    font-size: 2.5em;
    font-weight: bold;
    color: #2E7D32;
    margin: 15px 0;
    text-align: center;
}

.details {
    margin-top: 20px;
    padding-top: 20px;
    border-top: 1px solid #eee;
}

.details ul {
    list-style: none;
    padding: 10px 0;
}

.details li {
    padding: 5px 0;
    display: flex;
    align-items: center;
    gap: 10px;
}

.calculation {
    background: #f5f5f5;
    padding: 15px;
    border-radius: 10px;
    margin-top: 15px;
}

/* Info Section */
.info-section {
    display: flex;
    flex-direction: column;
    gap: 25px;
}

.info-card {
    background: white;
    padding: 25px;
    border-radius: 15px;
    box-shadow: 0 5px 15px rgba(0,0,0,0.05);
    border-left: 5px solid #2196F3;
}

.info-card h3 {
    color: #2196F3;
    margin-bottom: 15px;
    display: flex;
    align-items: center;
    gap: 10px;
}

.info-card ul {
    list-style: none;
    padding-left: 0;
}

.info-card li {
    padding: 8px 0;
    border-bottom: 1px solid #f0f0f0;
    display: flex;
    align-items: center;
    gap: 10px;
}

.info-card li:last-child {
    border-bottom: none;
}

/* Navigation */
.navigation {
    display: flex;
    gap: 15px;
    flex-wrap: wrap;
}

.nav-btn {
    flex: 1;
    background: #f0f4ff;
    color: #667eea;
    border: 2px solid #667eea;
    padding: 15px;
    border-radius: 10px;
    text-decoration: none;
    text-align: center;
    font-weight: 600;
    transition: all 0.3s;
    display: flex;
    align-items: center;
    justify-content: center;
    gap: 10px;
    min-width: 200px;
}

.nav-btn:hover {
    background: #667eea;
    color: white;
    transform: translateY(-2px);
}

/* Error Messages */
.error-message {
    background: #ffebee;
    color: #c62828;
    padding: 15px;
    border-radius: 10px;
    margin-bottom: 20px;
    border-left: 5px solid #c62828;
    display: flex;
    align-items: center;
    gap: 10px;
}

/* Footer */
footer {
    background: #f8f9fa;
    padding: 20px;
    text-align: center;
    border-top: 1px solid #e0e0e0;
    color: #666;
}

.model-status {
    margin-top: 10px;
    font-weight: 600;
}

.status-indicator {
    padding: 5px 15px;
    border-radius: 20px;
    font-size: 0.9em;
}

.status-indicator.active {
    background: #4CAF50;
    color: white;
}

.status-indicator.inactive {
    background: #f44336;
    color: white;
}

/* Responsive Design */
@media (max-width: 768px) {
    header h1 {
        font-size: 2em;
    }

    .main-content {
        padding: 20px;
    }

    .prediction-value {
        font-size: 2em;
    }

    .nav-btn {
        min-width: 100%;
    }
}



